name: Key Vault Testing

on:
  workflow_dispatch:
  push:
    paths:
      - './modules/key-vault.bicep/**' 
      - './parameters/key-vault-tests.json/**'


env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-A-DEV

jobs:
  build:
    name: Build and Lint Key Vault Bicep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Bicep Linter
        run: |
          echo "Building and validating Bicep file syntax..."
          az bicep build --file ./modules/key-vault.bicep

  validate:
    name: Validate Key Vault Deployment
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Dry Run Key Vault Deployment
        run: |
          echo "Performing a test run of the Key Vault deployment..."
          az deployment group what-if \
            --resource-group ${{ env.RESOURCE_GROUP_DEV }} \
            --template-file ./modules/key-vault.bicep \
            --parameters @parameters/key-vault-test.json

  deploy:
    name: Deploy Test Key Vault
    runs-on: ubuntu-latest
    needs: [build, validate]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Test Key Vault
        run: |
          echo "Deploying the Key Vault to the development environment..."
          az deployment group create \
            --resource-group ${{ env.RESOURCE_GROUP_DEV }} \
            --template-file ./modules/key-vault.bicep \
            --parameters @parameters/key-vault-test.json