name: safebank-infra-cd

on:
  workflow_run:
    workflows: [safebank-infra-ci]
    branches: [container_registry]
    types:
      - completed

env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-A-DEV
  RESOURCE_GROUP_UAT: BCSAI2024-DEVOPS-STUDENTS-A-UAT
  RESOURCE_GROUP_PROD: BCSAI2024-DEVOPS-STUDENTS-A-PROD
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  SUBSCRIPTION_ID_UAT: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  SUBSCRIPTION_ID_PROD: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: rorosaga

jobs:

  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      # Download the original Bicep file artifact
      - name: Download Bicep File
        uses: actions/download-artifact@v3
        with:
          name: bicep-files

      # Log into Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy the Bicep file to DEV
      - name: Deploy DEV
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: ./main.bicep
          parameters: ./parameters/dev.bicepparam appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }} appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }}
          deploymentName: ${{ env.USER_ALIAS }}-dev

  deploy-uat:
    runs-on: ubuntu-latest
    steps:
      # Download the original Bicep file artifact
      - name: Download Bicep File
        uses: actions/download-artifact@v3
        with:
          name: bicep-files

      # Log into Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy the Bicep file to UAT
      - name: Deploy UAT
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_UAT }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_UAT }}
          template: ./main.bicep
          parameters: ./parameters/uat.bicepparam appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }} appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }}
          deploymentName: ${{ env.USER_ALIAS }}-uat

  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      # Download the original Bicep file artifact
      - name: Download Bicep File
        uses: actions/download-artifact@v3
        with:
          name: bicep-files

      # Log into Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy the Bicep file to PROD
      - name: Deploy PROD
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_PROD }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_PROD }}
          template: ./main.bicep
          parameters: ./parameters/prod.bicepparam appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }} appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }}
          deploymentName: ${{ env.USER_ALIAS }}-prod